### ISSUE TITLE
disclaimer + question(s) / quiz to verify true adult age

### ISSUE THREAD

**Issue by FreshhhHub** [tstandiford/easy-age-verifier#126]
Hi, 

Congrats for creating this free plugin.  

I'm taking this legal age check very seriously and wonder if you can please consider 2 advanced options: 

1) add optional disclaimer that must be agreed in order to visit a website

2) add a (random) question or simple 3 questions quiz with form or sliders to verify real adult age instead of a simple YES/NO button that I'm afraid can be too easily bypassed by a child…  
 
Thanks for your hard work! 

All the best

**Comment by alexstandiford** [comment]
Hello!

Thank you for the kind words. I read this a while ago and just realized I never replied (so sorry!)

I think these features are a little beyond what I intended for Easy Age Verifier, however you could create a plugin that extends its functionality to do these things with some work.

the `eav_custom_modal_logic` hook should allow you to confirm the extra checks you're talking about are true

You could also add these additional fields with the custom verifier template:

https://github.com/alexstandiford/easy-age-verifier#custom-verifier-template

The only tricky part is going to be the Javascript, which needs some improvements.

I think if this issue would make any changes to EAV, it would simply be to implement hooks in the Javascript to allow developers to hook in custom modal logic just like we do with the PHP.
